using System.Security.Cryptography;
using System.Text;
using Marketplace.Application.Abstractions;
using Marketplace.Domain.Catalog;
using Marketplace.Domain.Common;
using Marketplace.Domain.Inventory;
using Marketplace.Domain.Sellers;

namespace Marketplace.Application.Catalog;

public sealed class CatalogManagementService
{
 private readonly ICatalogManagementRepository _repo; private readonly ISellerManagementRepository _sellers; private readonly IIdGenerator _ids; private readonly IUnitOfWork _uow;
 public CatalogManagementService(ICatalogManagementRepository repo,ISellerManagementRepository sellers,IIdGenerator ids,IUnitOfWork uow){_repo=repo;_sellers=sellers;_ids=ids;_uow=uow;}
 private async Task EnsureStore(long sellerId,long storeId,CancellationToken ct){var seller=await _sellers.GetSellerAsync(sellerId,ct)??throw new DomainException("Seller not found.");if(seller.Status!=SellerStatus.Active)throw new DomainException("Seller is not active.");if(!await _sellers.StoreBelongsToSellerAsync(storeId,sellerId,ct))throw new DomainException("Store does not belong to seller.");}
 public async Task<long> CreateProductAsync(long sellerId,long storeId,long categoryId,string name,string slug,string? description,long basePrice,bool hasVariants,CancellationToken ct=default){await EnsureStore(sellerId,storeId,ct);if(!await _repo.CategoryIsActiveAsync(categoryId,ct))throw new DomainException("Category is not active.");var p=Product.Create(await _ids.NextAsync(ct),storeId,categoryId,name,slug,basePrice,hasVariants);p.SetDescription(description);_repo.AddProduct(p);await _uow.SaveChangesAsync(ct);return p.Id;}
 public async Task<List<Product>> GetProductsAsync(long sellerId,long storeId,CancellationToken ct=default){await EnsureStore(sellerId,storeId,ct);return await _repo.GetProductsAsync(storeId,ct);}
 public async Task UpdateProductAsync(long sellerId,long productId,string name,string slug,string? description,long basePrice,CancellationToken ct=default){var p=await _repo.GetProductAsync(productId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);p.SetDescription(description);p.SetBasePrice(basePrice);await _uow.SaveChangesAsync(ct);}
 public async Task ActivateProductAsync(long sellerId,long productId,CancellationToken ct=default){var p=await _repo.GetProductAsync(productId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);p.Activate();await _uow.SaveChangesAsync(ct);}
 public async Task DeactivateProductAsync(long sellerId,long productId,CancellationToken ct=default){var p=await _repo.GetProductAsync(productId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);p.Deactivate();await _uow.SaveChangesAsync(ct);}
 public async Task<long> AddVariantAsync(long sellerId,long productId,string sku,string variantKey,long? price,CancellationToken ct=default){var p=await _repo.GetProductAsync(productId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);var v=ProductVariant.Create(await _ids.NextAsync(ct),productId,sku,variantKey,price);v.SetVariantKey(variantKey,SHA256.HashData(Encoding.UTF8.GetBytes(variantKey.Trim())));_repo.AddVariant(v);_repo.AddInventory(InventoryItem.Create(await _ids.NextAsync(ct),v.Id,0));await _uow.SaveChangesAsync(ct);return v.Id;}
 public async Task<List<ProductVariant>> GetVariantsAsync(long sellerId,long productId,CancellationToken ct=default){var p=await _repo.GetProductAsync(productId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);return await _repo.GetVariantsAsync(productId,ct);}
 public async Task UpdateVariantAsync(long sellerId,long variantId,string sku,string variantKey,long? price,bool active,CancellationToken ct=default){var v=await _repo.GetVariantAsync(variantId,ct)??throw new DomainException("Variant not found.");var p=await _repo.GetProductAsync(v.ProductId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);v.SetSku(sku);v.SetPrice(price);v.SetVariantKey(variantKey,SHA256.HashData(Encoding.UTF8.GetBytes(variantKey.Trim())));if(active)v.Activate();else v.Deactivate();await _uow.SaveChangesAsync(ct);}
 public async Task SetStockAsync(long sellerId,long variantId,long quantity,CancellationToken ct=default){if(quantity<0)throw new DomainException("Stock cannot be negative.");var v=await _repo.GetVariantAsync(variantId,ct)??throw new DomainException("Variant not found.");var p=await _repo.GetProductAsync(v.ProductId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);var inv=await _repo.GetInventoryAsync(variantId,ct)??throw new DomainException("Inventory not found.");if(quantity<inv.ReservedQuantity)throw new DomainException("Stock cannot be below reserved quantity.");if(quantity>inv.StockQuantity)inv.Increase(quantity-inv.StockQuantity);else if(quantity<inv.StockQuantity)inv.Decrease(inv.StockQuantity-quantity);await _uow.SaveChangesAsync(ct);}
 public async Task<long> CreateAttributeAsync(long sellerId,long storeId,string name,string slug,CancellationToken ct=default){await EnsureStore(sellerId,storeId,ct);var a=ProductAttribute.Create(await _ids.NextAsync(ct),storeId,name,slug);_repo.AddAttribute(a);await _uow.SaveChangesAsync(ct);return a.Id;}
 public async Task<long> CreateAttributeValueAsync(long sellerId,long attributeId,string value,string slug,CancellationToken ct=default){var a=await _repo.GetAttributeAsync(attributeId,ct)??throw new DomainException("Attribute not found.");await EnsureStore(sellerId,a.StoreId,ct);var v=ProductAttributeValue.Create(await _ids.NextAsync(ct),attributeId,value,slug);_repo.AddAttributeValue(v);await _uow.SaveChangesAsync(ct);return v.Id;}
 public async Task AssignAttributeAsync(long sellerId,long productId,long attributeId,CancellationToken ct=default){var p=await _repo.GetProductAsync(productId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);if(!await _repo.AttributeBelongsToStoreAsync(attributeId,p.StoreId,ct))throw new DomainException("Attribute does not belong to store.");_repo.AddProductAttributeAssignment(ProductAttributeAssignment.Create(await _ids.NextAsync(ct),productId,attributeId));await _uow.SaveChangesAsync(ct);}
 public async Task AssignVariantValueAsync(long sellerId,long variantId,long attributeValueId,CancellationToken ct=default){var v=await _repo.GetVariantAsync(variantId,ct)??throw new DomainException("Variant not found.");var p=await _repo.GetProductAsync(v.ProductId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);if(!await _repo.AttributeValueBelongsToStoreAsync(attributeValueId,p.StoreId,ct))throw new DomainException("Attribute value does not belong to store.");_repo.AddVariantAttributeValue(VariantAttributeValue.Create(await _ids.NextAsync(ct),variantId,attributeValueId));await _uow.SaveChangesAsync(ct);}
 public async Task<long> CreateWarrantyAsync(long sellerId,long storeId,string name,long price,CancellationToken ct=default){await EnsureStore(sellerId,storeId,ct);var w=Warranty.Create(await _ids.NextAsync(ct),storeId,name,price);_repo.AddWarranty(w);await _uow.SaveChangesAsync(ct);return w.Id;}
 public async Task LinkWarrantyAsync(long sellerId,long productId,long warrantyId,bool isDefault,CancellationToken ct=default){var p=await _repo.GetProductAsync(productId,ct)??throw new DomainException("Product not found.");await EnsureStore(sellerId,p.StoreId,ct);if(!await _repo.WarrantyBelongsToStoreAsync(warrantyId,p.StoreId,ct))throw new DomainException("Warranty does not belong to store.");_repo.AddProductWarranty(ProductWarranty.Create(await _ids.NextAsync(ct),productId,warrantyId,isDefault));await _uow.SaveChangesAsync(ct);}
}