using Marketplace.Application.Common.Abstractions;
using Marketplace.Application.Identity.Ports;
using Marketplace.Domain.Identity;
using Marketplace.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
namespace Marketplace.Infrastructure.Identity;
internal sealed class EfAuthService(MarketplaceDbContext db,IIdGenerator ids,JwtTokenService tokens):IAuthService
{
 public async Task<AuthResult> LoginAsync(string mobile,string password,string? ipAddress,CancellationToken ct=default){var user=await db.Users.SingleOrDefaultAsync(x=>x.Mobile==mobile.Trim(),ct)??throw new UnauthorizedAccessException("Invalid credentials.");if(!user.IsActive||user.IsLocked)throw new UnauthorizedAccessException("User is not available.");var credential=await db.UserCredentials.SingleOrDefaultAsync(x=>x.Id==user.Id,ct)??throw new UnauthorizedAccessException("Invalid credentials.");if(!PasswordHasher.Verify(password,credential.PasswordHash)){credential.RegisterFailedLogin();await db.SaveChangesAsync(ct);throw new UnauthorizedAccessException("Invalid credentials.");}credential.ResetFailedLogins();user.RecordLogin();var access=tokens.CreateAccessToken(user);var refresh=tokens.CreateRefreshToken();db.RefreshTokens.Add(RefreshToken.Create(ids.NewId(),user.Id,refresh.Hash,refresh.ExpiresAtUtc,ipAddress));await db.SaveChangesAsync(ct);return new(user.Id,access.Token,refresh.Raw,access.ExpiresAtUtc,refresh.ExpiresAtUtc);}
 public async Task<AuthResult> RefreshAsync(string refreshToken,string? ipAddress,CancellationToken ct=default){var hash=JwtTokenService.HashRefreshToken(refreshToken);var current=await db.RefreshTokens.SingleOrDefaultAsync(x=>x.TokenHash==hash,ct)??throw new UnauthorizedAccessException("Invalid refresh token.");if(!current.IsActive(DateTime.UtcNow))throw new UnauthorizedAccessException("Refresh token is expired or revoked.");var user=await db.Users.SingleOrDefaultAsync(x=>x.Id==current.UserId,ct)??throw new UnauthorizedAccessException("User not found.");if(!user.IsActive||user.IsLocked)throw new UnauthorizedAccessException("User is not available.");var access=tokens.CreateAccessToken(user);var next=tokens.CreateRefreshToken();var nextEntity=RefreshToken.Create(ids.NewId(),user.Id,next.Hash,next.ExpiresAtUtc,ipAddress);current.Revoke(ipAddress,nextEntity.Id);db.RefreshTokens.Add(nextEntity);await db.SaveChangesAsync(ct);return new(user.Id,access.Token,next.Raw,access.ExpiresAtUtc,next.ExpiresAtUtc);}
 public async Task RevokeRefreshTokenAsync(string refreshToken,string? ipAddress,CancellationToken ct=default){var token=await db.RefreshTokens.SingleOrDefaultAsync(x=>x.TokenHash==JwtTokenService.HashRefreshToken(refreshToken),ct);if(token is null)return;token.Revoke(ipAddress);await db.SaveChangesAsync(ct);}
}