using Marketplace.Domain.Common;
namespace Marketplace.Domain.Coupons;
public sealed class Coupon : AggregateRoot<long>
{
 private Coupon(){}
 public long StoreId{get;private set;} public string Code{get;private set;}=null!; public CouponDiscountType DiscountType{get;private set;} public long DiscountValue{get;private set;} public long? MaximumEligibleAmountIRR{get;private set;} public long? MinimumCartAmountIRR{get;private set;} public bool NewCustomerOnly{get;private set;} public int? MaxUsageCount{get;private set;} public int? MaxUsagePerCustomer{get;private set;} public DateTime? StartsAtUtc{get;private set;} public DateTime? ExpiresAtUtc{get;private set;} public bool IsActive{get;private set;} public bool AllowCampaignCombination{get;private set;} public int ReservedUsageCount{get;private set;} public int UsedUsageCount{get;private set;}
 public static Coupon Create(long id,long storeId,string code,CouponDiscountType type,long value,long? maxEligible,long? minCart,bool newOnly,int? maxUsage,int? maxPerCustomer,DateTime? starts,DateTime? expires,bool allowCampaign){if(string.IsNullOrWhiteSpace(code)||value<=0)throw new DomainException("Invalid coupon.");if(type==CouponDiscountType.Percent&&value>100)throw new DomainException("Invalid coupon percent.");return new(){Id=id,StoreId=storeId,Code=code.Trim().ToUpperInvariant(),DiscountType=type,DiscountValue=value,MaximumEligibleAmountIRR=maxEligible,MinimumCartAmountIRR=minCart,NewCustomerOnly=newOnly,MaxUsageCount=maxUsage,MaxUsagePerCustomer=maxPerCustomer,StartsAtUtc=starts,ExpiresAtUtc=expires,IsActive=true,AllowCampaignCombination=allowCampaign};}
 public long CalculateDiscount(long eligible){var capped=MaximumEligibleAmountIRR.HasValue?Math.Min(eligible,MaximumEligibleAmountIRR.Value):eligible;return DiscountType==CouponDiscountType.Percent?Math.Min(eligible,capped*DiscountValue/100):Math.Min(eligible,DiscountValue);} public void ReserveUsage(){if(MaxUsageCount.HasValue&&ReservedUsageCount+UsedUsageCount>=MaxUsageCount)throw new DomainException("Coupon usage limit reached.");ReservedUsageCount++;} public void MarkUsageUsed(){if(ReservedUsageCount<=0)throw new DomainException("No reserved usage.");ReservedUsageCount--;UsedUsageCount++;} public void ReleaseUsage(){if(ReservedUsageCount<=0)throw new DomainException("No reserved usage.");ReservedUsageCount--;}
}
public enum CouponDiscountType:byte{Percent=1,Fixed=2}
